# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='test',
            new_name='text',
        ),
    ]
